### ISSUE TITLE
Command Timestamp

### ISSUE THREAD

**Issue by grybka** [kofron/dripline#18]
When dripline processes a command, it should stamp it with a time.  Mostly it would be helpful in debugging to figure out what happened when.

**Comment by grybka** [comment]
Ooh, or maybe couchdb should automatically timestamp a command when its received.  Or keep a both received and executed stamp?

**Comment by kofron** [comment]
Could you be more specific in terms of what you'd like to see?

**Comment by grybka** [comment]
```
I was submitting commands and nothing was happening, so I wanted to
```

validate that my commands were actually showing up in the right format.
It struck me that it would be nice to make a view where commands are
sorted by date entered so I could ask "what's the most recent command
issued?".  I'm not entirely sure what software would have responsibility
to fill in the field.  It looks like couchdb doesn't have an easy way to
add fields every time a document is submitted, so either the command
submitter should include a "time_submitted" field, or dripline should
add a "time_processed" field, or both.  For the time being, I'll include
a "time_submitted" field.

**Comment by kofron** [comment]
Got it.

On Mon, May 7, 2012 at 10:00 PM, Gray Rybka <
reply@reply.github.com

**Comment by kofron** [comment]
There is now a "heartbeat" channel that tells you if dripline is running or not.  This should suffice.
